version: 1
disable_existing_loggers: false

formatters:
  simple:
    format: '%(asctime)s [%(levelname)s|%(module)s|L%(lineno)d] %(message)s'
    datefmt: '%Y-%m-%dT%H:%M:%S%z'

handlers:
  stderr:
    class: logging.StreamHandler
    level: WARNING
    formatter: simple
    stream: ext://sys.stderr

  file_handler:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: simple
    filename: logs/labq_rag.log
    maxBytes: 10485760  # 10MB
    backupCount: 5
    encoding: utf-8

  queue_handler:
    class: logging.handlers.QueueHandler
    handlers:
      - stderr
      - file_handler
    respect_handler_level: true

loggers:
  root:
    level: DEBUG
    handlers:
      - queue_handler
